name: BundleWatch

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.17.0
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Next.js App
        run: pnpm build

      - name: Run BundleWatch
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
          CI_REPO_OWNER: ${{ github.repository_owner }}
          CI_REPO_NAME: ${{ github.event.repository.name }}
          CI_COMMIT_SHA: ${{ github.sha }}
          CI_BRANCH: ${{ github.ref_name }}
          CI_BRANCH_BASE: ${{ github.base_ref }}
        run: pnpm exec bundlewatch
