name: 'Next.js Bundle Analysis'

on:
  pull_request:
  push:
    branches:
      - main # change this if your default branch is named differently
  workflow_dispatch:

defaults:
  run:
    working-directory: ./

permissions:
  contents: read
  actions: read
  pull-requests: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: 20.17.0 # Or your preferred version
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Restore next build cache
        uses: actions/cache@v3
        id: restore-build-cache
        env:
          cache-name: cache-next-build
        with:
          path: .next/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Build Next.js app
        run: pnpm next build

      - name: Analyze bundle with details
        run: npx -p nextjs-bundle-analysis report --details

      - name: Upload bundle analysis results
        uses: actions/upload-artifact@v4
        with:
          name: bundle-analysis-results
          path: .next/analyze

      - name: Download base branch bundle stats
        uses: dawidd6/action-download-artifact@v2
        if: success() && github.event.number
        with:
          workflow: nextjs_bundle_analysis.yml
          branch: ${{ github.event.pull_request.base.ref }}
          path: .next/analyze/base

      - name: Compare with base branch bundle
        if: success() && github.event.number
        run: npx -p nextjs-bundle-analysis compare --details # Add --details here as well

      - name: Generate detailed comment body
        id: generate-comment
        if: success() && github.event.number
        run: |
          echo "body<<EOF" >> $GITHUB_OUTPUT
          cat .next/analyze/__bundle_analysis_comment.txt | while read line; do
            echo "$line" >> $GITHUB_OUTPUT
          done
          # Include detailed page analysis in the comment
          if [[ -f ".next/analyze/__bundle_analysis_details.txt" ]]; then
            echo "" >> $GITHUB_OUTPUT
            echo "<details><summary>Detailed Page Analysis</summary>" >> $GITHUB_OUTPUT
            cat .next/analyze/__bundle_analysis_details.txt | while read line; do
              echo "$line" >> $GITHUB_OUTPUT
            done
            echo "</details>" >> $GITHUB_OUTPUT
          fi
          echo EOF >> $GITHUB_OUTPUT


      - name: Find Comment
        uses: peter-evans/find-comment@v2
        if: success() && github.event.number
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          body-includes: ''

      - name: Create Comment
        uses: peter-evans/create-or-update-comment@v2
        if: success() && github.event.number && steps.fc.outputs.comment-id == 0
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.generate-comment.outputs.body }}

      - name: Update Comment
        uses: peter-evans/create-or-update-comment@v2
        if: success() && github.event.number && steps.fc.outputs.comment-id != 0
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.generate-comment.outputs.body }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace